---
layout: post
title: Printing from Revit
date: 2010-05-30 13:13:12
author: Eric Stimmel
---

They needed to print a set of drawings showing the revision deltas (those little triangles with numbers in them identifying which revision each change was a part of) but not the revision clouds. There were lots of these revision deltas and clouds (as there are with all projects) and they just needed a clean set. Seems reasonable and easy enough, just freeze the layer(s) with the revision clouds and not the layers with the revision deltas - this can be done with a simple AutoCAD script or in our case we have some custom tools that allow us to manage layer visibility externally, so just make a few adjustments and voila, done. Of course it wasn't that simple (or I wouldn't be writing this) and if you've ever had to deal with something like this, I'm sure you know where I'm going... the revision clouds and deltas were on the same layer in some files, they were on different, but inconsistently named layers in other files, other linework and text were drawn on the same layers, some in the sheet file and others in the annotation file (an xref), etc. It was a big task considering there were 1000+ sheets and at least that many more xrefs that needed to be checked. (discus the script) ;; ;; ChLayer.lsp ;; ;; ChLayer ;; Routine to select rev clouds on a specified layer(s), move them to a non-plotting layer ;; then freeze the new layer. ;; by Eric Stimmel eric.stimmel@som.com ;; ;; last updated 9/24/2008 ;; (defun c:chlayer (/ lay\_name lay\_name\_new ss1 n index ent1 a1 a2 b1) ; Define the function (setq lay\_name "A-ANNO-R\*") ; Specify the layer(s) that the rev clouds are currently on (setq lay\_name\_new "A-ANNO-REVS-NPLT") ; Define target layer to change rev clouds to (setq ss1 (ssget "X" (list (cons 0 "LWPOLYLINE")(cons 8 lay\_name)))) ; Select all lwpolylines on the specified layer (setq n (sslength ss1)) ; Measure the number of entities in the selection set ss1 (setq index 0) ; Set the variable called index to 0 (repeat n ; Begin the loop that pages through the selection set (setq ent1 (entget (ssname ss1 index))) ; Get the entity list and assigns it to ent1 (setq b1 (subst (cons 8 lay\_name\_new) (assoc 8 ent1) ent1 ) ) ; Change the layer code for each object in the set (entmod b1) ; Modify the the entity's layer in the drawing (setq index (+ index 1)) ; Increas the index variable by 1 and loop ) ; Close the repeat loop (command "LAYER" "FREEZE" "A-ANNO-REVS-NPLT" "") ; Freeze the new layer (princ) ; Exit quitely ) ; Close the function (c:chlayer) ; Run the function This is both the beauty and the horror of AutoCAD - you can access the data from every angle imaginable and modify it a million different ways with a multiple programming languages, but the data is almost never "intelligent" and, until very recently, not object oriented (to misappropriate a term) by which I mean multiple drawings are only related insofar as someone has drawn them correctly. One is independently drawing the elevations and sections of an imaginary box rather than modeling the box and viewing it from different angles.
